use serde::{Deserialize, Serialize};
use std::path::Path;

use crate::todo::{TodoItem, TodoPriority, TodoStatus};

/// A single task within a plan phase.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanTask {
    pub description: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_input: Option<serde_json::Value>,
}

/// A phase in an implementation plan.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanPhase {
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub tasks: Vec<PlanTask>,
}

/// A structured implementation plan generated by the planner model.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanArtifact {
    pub title: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub phases: Vec<PlanPhase>,
}

impl PlanArtifact {
    /// Convert the plan into todo items for tracking progress.
    #[must_use] 
    pub fn to_todos(&self) -> Vec<TodoItem> {
        let mut todos = Vec::new();
        for (phase_idx, phase) in self.phases.iter().enumerate() {
            for (task_idx, task) in phase.tasks.iter().enumerate() {
                todos.push(TodoItem {
                    id: format!("plan-{phase_idx}-{task_idx}"),
                    content: format!("[{}] {}", phase.name, task.description),
                    status: TodoStatus::Pending,
                    priority: TodoPriority::High,
                });
            }
        }
        todos
    }

    /// Count total tasks across all phases.
    #[must_use]
    pub fn total_tasks(&self) -> usize {
        self.phases.iter().map(|p| p.tasks.len()).sum()
    }

    /// Count completed tasks (those not pending) based on todo status.
    #[must_use]
    pub fn completed_tasks(&self, todos: &[TodoItem]) -> usize {
        todos
            .iter()
            .filter(|t| t.status != TodoStatus::Pending && t.status != TodoStatus::InProgress)
            .count()
    }

    /// Save the plan to a JSON file.
    pub fn save(&self, path: &Path) -> Result<(), std::io::Error> {
        let json = serde_json::to_string_pretty(self)
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))?;
        std::fs::write(path, json)
    }

    /// Load a plan from a JSON file.
    pub fn load(path: &Path) -> Result<Self, std::io::Error> {
        let json = std::fs::read_to_string(path)?;
        serde_json::from_str(&json)
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))
    }
}

/// Extract JSON from a markdown code block in assistant text.
#[must_use] 
pub fn extract_json_from_response(text: &str) -> Option<String> {
    // Look for ```json ... ``` block
    if let Some(start) = text.find("```json") {
        let after_start = &text[start + 7..];
        if let Some(end) = after_start.find("```") {
            return Some(after_start[..end].trim().to_string());
        }
    }
    // Fallback: look for ``` ... ``` block
    if let Some(start) = text.find("```") {
        let after_start = &text[start + 3..];
        if let Some(end) = after_start.find("```") {
            return Some(after_start[..end].trim().to_string());
        }
    }
    // Fallback: try to find JSON object directly
    if let Some(start) = text.find('{') {
        if let Some(end) = text.rfind('}') {
            if end > start {
                return Some(text[start..=end].to_string());
            }
        }
    }
    None
}

/// Build the planning prompt that asks the model to generate a structured plan.
#[must_use]
pub fn build_plan_prompt(description: &str) -> String {
    format!(
        r#"You are an expert software architect and planner. Create a detailed implementation plan for the following task.

Task: {description}

Output your plan as a single JSON object inside a ```json code block. Use this exact structure:

{{
  "title": "Short title for the plan",
  "description": "One-sentence summary of the overall approach",
  "phases": [
    {{
      "name": "Phase 1: Research and Analysis",
      "description": "What this phase accomplishes",
      "tasks": [
        {{
          "description": "Specific actionable task description",
          "tool": "optional_tool_name like read_file or bash",
          "tool_input": {{}}
        }}
      ]
    }}
  ]
}}

Guidelines:
- Break the work into 2-5 phases
- Each phase should have 1-5 specific tasks
- Tasks should be actionable and concrete
- Only include "tool" and "tool_input" when you know the exact tool and parameters
- Do NOT use any tools — just return the JSON plan
- Ensure the JSON is valid and parseable
- Focus on code changes, file operations, and verification steps"#
    )
}

/// Build a concise plan summary for display.
#[must_use]
pub fn format_plan_summary(plan: &PlanArtifact) -> String {
    let mut lines = vec![format!("## Plan: {}\n", plan.title)];
    if let Some(ref desc) = plan.description {
        lines.push(format!("{desc}\n"));
    }
    for (i, phase) in plan.phases.iter().enumerate() {
        lines.push(format!("\n**Phase {}: {}**", i + 1, phase.name));
        if let Some(ref desc) = phase.description {
            lines.push(format!("  {desc}"));
        }
        for (j, task) in phase.tasks.iter().enumerate() {
            let tool_hint = task
                .tool
                .as_ref()
                .map(|t| format!(" (`{t}`)"))
                .unwrap_or_default();
            lines.push(format!("  {}. {}{}", j + 1, task.description, tool_hint));
        }
    }
    lines.push(format!(
        "\n*Total: {} tasks in {} phases*",
        plan.total_tasks(),
        plan.phases.len()
    ));
    lines.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extracts_json_from_markdown_block() {
        let text = r#"Here is the plan:

```json
{"title": "Test", "phases": []}
```

Hope this helps!"#;
        let json = extract_json_from_response(text).unwrap();
        assert!(json.contains("\"title\": \"Test\""));
    }

    #[test]
    fn extracts_json_without_language_tag() {
        let text = r#"```
{"title": "Test", "phases": []}
```"#;
        let json = extract_json_from_response(text).unwrap();
        assert!(json.contains("\"title\": \"Test\""));
    }

    #[test]
    fn extracts_bare_json() {
        let text = r#"Some text before {"title": "Test", "phases": []} and after"#;
        let json = extract_json_from_response(text).unwrap();
        assert!(json.contains("\"title\": \"Test\""));
    }

    #[test]
    fn plan_to_todos_conversion() {
        let plan = PlanArtifact {
            title: "Fix bug".to_string(),
            description: None,
            phases: vec![
                PlanPhase {
                    name: "Research".to_string(),
                    description: None,
                    tasks: vec![PlanTask {
                        description: "Read source file".to_string(),
                        tool: Some("read_file".to_string()),
                        tool_input: None,
                    }],
                },
                PlanPhase {
                    name: "Fix".to_string(),
                    description: None,
                    tasks: vec![PlanTask {
                        description: "Edit file".to_string(),
                        tool: Some("edit_file".to_string()),
                        tool_input: None,
                    }],
                },
            ],
        };
        let todos = plan.to_todos();
        assert_eq!(todos.len(), 2);
        assert_eq!(todos[0].content, "[Research] Read source file");
        assert_eq!(todos[0].status, TodoStatus::Pending);
    }
}
