// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	smokeTest: () => __TAURI_INVOKE<string>("smoke_test"),
	/** spawn_agent: spawn a new agent with task, model, and optional budget. Worktree branch is derived from the task on the Rust side. Returns the new agent ID. */
	spawnAgent: (task: string, model: string, budgetDollars: number | null) =>
		typedError<string, string>(__TAURI_INVOKE("spawn_agent", { task, model, budgetDollars })),
	/**  list_agents: returns all agent IDs currently in the supervisor registry. */
	listAgents: () => __TAURI_INVOKE<string[]>("list_agents"),
	/**  stop_agent: sends stop signal to the named agent (async because stop_agent() is async). */
	stopAgent: (agentId: string) => typedError<null, string>(__TAURI_INVOKE("stop_agent", { agentId })),
	/** respond_to_permission: resolves a pending permission prompt (D-10 / D-11). */
	respondToPermission: (promptId: string, decision: PermissionDecision) => typedError<null, string>(__TAURI_INVOKE("respond_to_permission", { promptId, decision })),
	/** test_permission_prompt: emits a synthetic permission-request event for smoke testing. */
	testPermissionPrompt: () => typedError<string, string>(__TAURI_INVOKE("test_permission_prompt")),
	/** run_agent_turn: send a user message to a running agent (per D-03). */
	runAgentTurn: (agentId: string, message: string) => typedError<null, string>(__TAURI_INVOKE("run_agent_turn", { agentId, message })),
	/** list_models: returns configured model names for the model selector (UI-08). */
	listModels: () => __TAURI_INVOKE<string[]>("list_models"),
	/** list_sessions: returns saved session metadata sorted newest first (UI-06). */
	listSessions: () => __TAURI_INVOKE<SessionMeta[]>("list_sessions"),
	/** load_session: reads session JSON by id; id must be alphanumeric+hyphens only. */
	loadSession: (id: string) => typedError<string, string>(__TAURI_INVOKE("load_session", { id })),
	/** delete_session: removes session file by id. */
	deleteSession: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_session", { id })),
	/** save_session: writes session JSON to ~/.xolotl-code/sessions/{id}.json */
	saveSession: (id: string, json: string) => typedError<null, string>(__TAURI_INVOKE("save_session", { id, json })),
};

/* Types */
/**
 *  Events emitted by a supervised agent.
 * 
 *  This enum is the single event schema for both in-process channels (D-01)
 *  and NDJSON stdout serialization from child-process workers (D-04).
 *  All variants must remain serde-compatible — do NOT add non-serializable fields.
 */
export type AgentEvent = ({ StateChanged: AgentState }) & { Error?: never; ToolCallCompleted?: never; ToolCallStarted?: never; TurnCompleted?: never; TextDelta?: never } | ({ ToolCallStarted: {
	tool: string,
	input: string,
} }) & { Error?: never; StateChanged?: never; ToolCallCompleted?: never; TurnCompleted?: never; TextDelta?: never } | ({ ToolCallCompleted: {
	tool: string,
	output: string,
} }) & { Error?: never; StateChanged?: never; ToolCallStarted?: never; TurnCompleted?: never; TextDelta?: never } | ({ TurnCompleted: {
	usage: TokenUsage,
} }) & { Error?: never; StateChanged?: never; ToolCallCompleted?: never; ToolCallStarted?: never; TextDelta?: never } | ({ Error: {
	message: string,
} }) & { StateChanged?: never; ToolCallCompleted?: never; ToolCallStarted?: never; TurnCompleted?: never; TextDelta?: never } | ({ TextDelta: string }) & { Error?: never; StateChanged?: never; ToolCallCompleted?: never; ToolCallStarted?: never; TurnCompleted?: never };

/**
 *  Stable identifier for a supervised agent.
 *  Newtype over String — use AgentId::new() to generate a unique id.
 */
export type AgentId = string;

/**
 *  Typed state machine for a supervised agent.
 * 
 *  Valid transitions (can_transition_to returns true):
 *  - Idle → Planning, Executing
 *  - Planning → Executing, Failed
 *  - Executing → Waiting, Done, Failed
 *  - Waiting → Executing, Failed
 *  - Done → (terminal — no transitions)
 *  - Failed → (terminal — no transitions)
 */
export type AgentState = "Idle" | "Planning" | "Executing" | 
/**  Blocked on a permission prompt or context pull. */
"Waiting" | "Done" | "Failed";

/** Frontend-facing decision type with three options (D-12). */
export type PermissionDecision = "Allow" | "Deny" | "AlwaysAllow";

export type TokenUsage = {
	input_tokens: number,
	output_tokens: number,
	cache_creation_input_tokens: number,
	cache_read_input_tokens: number,
};

export type SessionMeta = {
	id: string,
	title: string,
	created_at: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        // WR-04: treat all caught values as errors — do NOT re-throw Error instances.
        // Re-throwing causes unhandled promise rejections in callers that only check
        // result.status and have no surrounding try/catch.
        return { status: "error", error: e as E };
    }
}

