// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	smokeTest: () => __TAURI_INVOKE<string>("smoke_test"),
	/**
	 *  spawn_agent: creates an agent with task/model/optional budget.
	 * 
	 *  `chat_mode = true` (used by the chat composer) skips spawn_agent_executor,
	 *  which would otherwise launch the autonomous `xolotl` CLI subprocess.
	 *  In chat we only need the agent handle as an event channel for
	 *  run_agent_turn — the CLI subprocess would race with the streaming API
	 *  call and pollute the chat with its own output.
	 * 
	 *  `chat_mode = false` (Agents panel) keeps the original autonomous behavior.
	 */
	spawnAgent: (task: string, model: string, budgetDollars: number | null, chatMode: boolean | null) => typedError<string, string>(__TAURI_INVOKE("spawn_agent", { task, model, budgetDollars, chatMode })),
	listAgents: () => __TAURI_INVOKE<string[]>("list_agents"),
	stopAgent: (agentId: string) => typedError<null, string>(__TAURI_INVOKE("stop_agent", { agentId })),
	respondToPermission: (promptId: string, decision: PermissionDecision) => typedError<null, string>(__TAURI_INVOKE("respond_to_permission", { promptId, decision })),
	testPermissionPrompt: () => typedError<string, string>(__TAURI_INVOKE("test_permission_prompt")),
	/**
	 *  run_agent_turn: send message history to the AI and stream back the response.
	 *  Messages is the full conversation including the new user message.
	 *  Model is passed explicitly to enable per-turn model switching.
	 */
	runAgentTurn: (agentId: string, messages: ChatMessage[], model: string) => typedError<null, string>(__TAURI_INVOKE("run_agent_turn", { agentId, messages, model })),
	listModels: () => __TAURI_INVOKE<string[]>("list_models"),
	listPromptCommands: () => __TAURI_INVOKE<PromptCommand[]>("list_prompt_commands"),
	listSessions: () => __TAURI_INVOKE<SessionMeta[]>("list_sessions"),
	loadSession: (id: string) => typedError<string, string>(__TAURI_INVOKE("load_session", { id })),
	deleteSession: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_session", { id })),
	saveSession: (id: string, json: string) => typedError<null, string>(__TAURI_INVOKE("save_session", { id, json })),
	launchTeam: (roles: RoleConfig[]) => typedError<GroupLaunchResult, string>(__TAURI_INVOKE("launch_team", { roles })),
	launchSwarm: (count: number, objective: string, model: string) => typedError<GroupLaunchResult, string>(__TAURI_INVOKE("launch_swarm", { count, objective, model })),
	getWorktreeDiff: (agentId: string) => typedError<FileDiff[], string>(__TAURI_INVOKE("get_worktree_diff", { agentId })),
	mergeWorktrees: (groupId: string, agentIds: string[]) => typedError<null, string>(__TAURI_INVOKE("merge_worktrees", { groupId, agentIds })),
	/**
	 *  start_eval: starts selected models on the same prompt in parallel.
	 *  Emits "eval-event:{eval_id}" events as each model streams.
	 *  Saves result to ~/.xolotl-code/evals/{eval_id}.json when all complete.
	 */
	startEval: (prompt: string, models: string[]) => typedError<string, string>(__TAURI_INVOKE("start_eval", { prompt, models })),
	listEvals: () => __TAURI_INVOKE<EvalMeta[]>("list_evals"),
	loadEval: (id: string) => typedError<string, string>(__TAURI_INVOKE("load_eval", { id })),
	deleteEval: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_eval", { id })),
	/**  Reveal a persisted eval result JSON file in Finder. */
	revealEvalResultInFinder: (id: string) => typedError<null, string>(__TAURI_INVOKE("reveal_eval_result_in_finder", { id })),
	/**  Reveal the generated eval artifacts folder in Finder, creating it if needed. */
	revealEvalArtifactsInFinder: () => typedError<null, string>(__TAURI_INVOKE("reveal_eval_artifacts_in_finder")),
	/**
	 *  save_human_scores: updates the human_scores map in a stored eval.
	 *  scores_json is a JSON object mapping model name → HumanScores.
	 */
	saveHumanScores: (id: string, scoresJson: string) => typedError<null, string>(__TAURI_INVOKE("save_human_scores", { id, scoresJson })),
	/**
	 *  save_manual_reviews: updates the personal post-eval review map in a stored eval.
	 *  reviews_json is a JSON object mapping model name -> ManualReview.
	 */
	saveManualReviews: (id: string, reviewsJson: string) => typedError<null, string>(__TAURI_INVOKE("save_manual_reviews", { id, reviewsJson })),
	listEvalSuites: () => __TAURI_INVOKE<EvalSuite[]>("list_eval_suites"),
	/**
	 *  run_eval_suite: runs every prompt of a suite across selected models in parallel.
	 *  Returns a `suite_run_id` shared by all the per-prompt EvalResults written to disk.
	 */
	runEvalSuite: (suiteId: string, models: string[]) => typedError<string, string>(__TAURI_INVOKE("run_eval_suite", { suiteId, models })),
	/**
	 *  LLM-as-judge: have `judge_model` score every response in a stored eval against
	 *  the 8-dimension rubric. Result is saved into the eval's `judge` field.
	 */
	runLlmJudge: (id: string, judgeModel: string) => typedError<string, string>(__TAURI_INVOKE("run_llm_judge", { id, judgeModel })),
	/**
	 *  start_goal_eval: like start_eval but tagged as a goal eval and (optionally)
	 *  streams a live reasoning supervisor that flags issues as the model thinks.
	 *  `live_supervisor` flips on the per-model windowed flag-judge.
	 */
	startGoalEval: (goal: string, models: string[], liveSupervisor: boolean, supervisorModel: string | null) => typedError<string, string>(__TAURI_INVOKE("start_goal_eval", { goal, models, liveSupervisor, supervisorModel })),
	/**
	 *  Post-hoc goal grader. For each model in a stored eval, score the 5 reasoning
	 *  axes (1–5 each) with an evidence quote, extract retrospective flags, and
	 *  write a one-line summary. Results saved into `goal_grades` on disk.
	 */
	runGoalGrade: (id: string, judgeModel: string) => typedError<string, string>(__TAURI_INVOKE("run_goal_grade", { id, judgeModel })),
	listSkills: () => __TAURI_INVOKE<SkillManifest[]>("list_skills"),
	readSkill: (name: string) => typedError<string, string>(__TAURI_INVOKE("read_skill", { name })),
	listMcpServers: () => __TAURI_INVOKE<McpServerConfig[]>("list_mcp_servers"),
	/**
	 *  Test an MCP server's reachability. For stdio: spawn it and send a JSON-RPC
	 *  `initialize` ping (handshake required by the MCP spec). For http: GET / and
	 *  check for any response (200/404 both prove the host is up).
	 */
	testMcpServer: (name: string) => __TAURI_INVOKE<McpTestResult>("test_mcp_server", { name }),
	/**  Returns which providers have an API key configured and where it came from. */
	getApiKeyStatus: () => __TAURI_INVOKE<{ [key in string]: ApiKeyProviderStatus }>("get_api_key_status"),
	/**  Load macOS productivity preferences that are safe to keep in config.json. */
	getMacProductivitySettings: () => __TAURI_INVOKE<MacProductivitySettings>("get_mac_productivity_settings"),
	/**
	 *  Move one legacy config-file API key into macOS Keychain without exposing it
	 *  to the frontend. Available on macOS only.
	 */
	migrateApiKeyToKeychain: (provider: string) => typedError<ApiKeyProviderStatus, string>(__TAURI_INVOKE("migrate_api_key_to_keychain", { provider })),
	/**
	 *  Set the preferred external editor. Use an app name such as "Visual Studio
	 *  Code" or "Cursor" on macOS, or a full executable path for CLI launchers.
	 */
	setExternalEditor: (editor: string) => typedError<MacProductivitySettings, string>(__TAURI_INVOKE("set_external_editor", { editor })),
	/**  Set the opt-in global shortcut that brings Xolotl Code to the front. */
	setMacGlobalHotkeySettings: (settings: MacGlobalHotkeySettings) => typedError<MacProductivitySettings, string>(__TAURI_INVOKE("set_mac_global_hotkey_settings", { settings })),
	/**  Set opt-in macOS notification preferences for long-running work. */
	setMacNotificationSettings: (settings: MacNotificationSettings) => typedError<MacProductivitySettings, string>(__TAURI_INVOKE("set_mac_notification_settings", { settings })),
	/**
	 *  Save an API key for a provider. Pass an empty string to clear the key.
	 *  On macOS app-saved keys are stored in Keychain; other config.json fields
	 *  are still preserved for CLI-written settings.
	 */
	setApiKey: (provider: string, key: string) => typedError<null, string>(__TAURI_INVOKE("set_api_key", { provider, key })),
	/**  Open a path in the configured external editor without using a shell. */
	openPathInExternalEditor: (path: string) => typedError<null, string>(__TAURI_INVOKE("open_path_in_external_editor", { path })),
	/**
	 *  Test connectivity to an AI provider using its configured API key.
	 *  Returns "Connected to <provider>" on success.
	 */
	testApiConnection: (provider: string) => typedError<string, string>(__TAURI_INVOKE("test_api_connection", { provider })),
	startEvalArtifact: (request: EvalArtifactRequest) => typedError<EvalArtifactLaunchResult, string>(__TAURI_INVOKE("start_eval_artifact", { request })),
	/**
	 *  Aggregate every persisted eval's reliability metrics (P6.1) into per-model
	 *  reliability profiles under `~/.xolotl-code/profiles/<model>.json` (P6.2).
	 * 
	 *  Pure aggregation lives in the `runtime` crate (offline-tested); this command
	 *  just resolves the home directories and reports what was produced.
	 */
	buildReliabilityProfiles: () => typedError<ProfileBuildResult, string>(__TAURI_INVOKE("build_reliability_profiles")),
	/**
	 *  Derive propose-only `ModelHints` overrides from each reliability profile and
	 *  write them to `~/.xolotl-code/profiles/proposals/<model>.json` (P6.3).
	 * 
	 *  Reviewable only — never merges into the shipped hint defaults.
	 */
	buildHintProposals: () => typedError<ProposalBuildResult, string>(__TAURI_INVOKE("build_hint_proposals")),
	/**  List the per-model reliability profiles written by `build_reliability_profiles` (P6.4). */
	listReliabilityProfiles: () => __TAURI_INVOKE<ReliabilityProfile[]>("list_reliability_profiles"),
	/**  List the per-model propose-only hint proposals written by `build_hint_proposals` (P6.4). */
	listHintProposals: () => __TAURI_INVOKE<HintProposal[]>("list_hint_proposals"),
	cleanupEvalProcesses: () => __TAURI_INVOKE<number>("cleanup_eval_processes"),
	cancelChatTurn: (turnId: string) => __TAURI_INVOKE<boolean>("cancel_chat_turn", { turnId }),
	/**
	 *  chat_turn: streaming chat that bypasses the agent/worktree system entirely.
	 * 
	 *  This is for the conversational chat UX (vibe-coding style, like Claude or
	 *  ChatGPT). Unlike run_agent_turn, it does NOT spawn an AgentSupervisor entry,
	 *  create a git worktree, or maintain any per-session state on the Rust side —
	 *  it just streams from the LLM and emits events on `chat-event:{turn_id}`.
	 * 
	 *  The caller (frontend) generates `turn_id`, subscribes to the channel BEFORE
	 *  invoking this command (to avoid losing the first events), then awaits a
	 *  TurnCompleted or Error event to know the turn finished.
	 */
	chatTurn: (turnId: string, messages: ChatMessage[], model: string, enabledSkills: string[] | null, reasoningEffort: string | null, cwd: string | null) => typedError<null, string>(__TAURI_INVOKE("chat_turn", { turnId, messages, model, enabledSkills, reasoningEffort, cwd })),
	launchProjectPaths: () => __TAURI_INVOKE<string[]>("launch_project_paths"),
	/**  List saved quick-access projects, most-recently-opened first. */
	listProjects: () => __TAURI_INVOKE<Project[]>("list_projects"),
	/**
	 *  Add (or refresh) a project by directory path. Validates the directory
	 *  exists, canonicalizes it, dedupes, and returns the updated list.
	 */
	addProject: (path: string) => typedError<Project[], string>(__TAURI_INVOKE("add_project", { path })),
	/**  Remove a project from quick access (does not touch the directory on disk). */
	removeProject: (path: string) => typedError<Project[], string>(__TAURI_INVOKE("remove_project", { path })),
	/**  Mark a project as just-opened (bumps it to the top of the list). */
	touchProject: (path: string) => typedError<null, string>(__TAURI_INVOKE("touch_project", { path })),
	/**
	 *  Reveal a file or folder in the platform file manager. On macOS this selects
	 *  the item in Finder via `open -R`.
	 */
	revealInFinder: (path: string) => typedError<null, string>(__TAURI_INVOKE("reveal_in_finder", { path })),
	refreshNativeMenu: () => typedError<null, string>(__TAURI_INVOKE("refresh_native_menu")),
	/**
	 *  Open a native folder picker and return the chosen directory (or `None` if
	 *  the user cancelled).
	 */
	pickDirectory: () => typedError<string | null, string>(__TAURI_INVOKE("pick_directory")),
	/**
	 *  List the immediate children of a directory (directories first, then files),
	 *  for the sidebar file browser.
	 */
	browseDirectory: (path: string) => typedError<DirListing, string>(__TAURI_INVOKE("browse_directory", { path })),
	/**
	 *  Convert a PDF file to Markdown (`format = "md"`) or JSON (`format = "json"`)
	 *  using deterministic extraction — no AI, no OCR, no network.
	 */
	convertPdf: (path: string, format: string) => typedError<string, string>(__TAURI_INVOKE("convert_pdf", { path, format })),
	/**  Spawn a new terminal. Returns its metadata (including the generated id). */
	terminalSpawn: (cwd: string | null, shell: string | null, cols: number, rows: number) => typedError<TerminalInfo, string>(__TAURI_INVOKE("terminal_spawn", { cwd, shell, cols, rows })),
	/**  Write input (keystrokes) to a terminal. */
	terminalWrite: (id: string, data: string) => typedError<null, string>(__TAURI_INVOKE("terminal_write", { id, data })),
	/**  Resize a terminal's PTY. */
	terminalResize: (id: string, cols: number, rows: number) => typedError<null, string>(__TAURI_INVOKE("terminal_resize", { id, cols, rows })),
	/**  Kill a terminal and remove it from the registry. */
	terminalKill: (id: string) => typedError<null, string>(__TAURI_INVOKE("terminal_kill", { id })),
	/**  Kill all live terminals owned by this app instance. */
	terminalKillAll: () => __TAURI_INVOKE<number>("terminal_kill_all"),
	/**  List all live terminals. */
	terminalList: () => __TAURI_INVOKE<TerminalInfo[]>("terminal_list"),
	createCivSession: (config: CivSessionConfig) => typedError<string, string>(__TAURI_INVOKE("create_civ_session", { config })),
	listCivSessions: () => __TAURI_INVOKE<CivSessionMeta[]>("list_civ_sessions"),
	loadCivSession: (id: string) => typedError<string, string>(__TAURI_INVOKE("load_civ_session", { id })),
	deleteCivSession: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_civ_session", { id })),
	applyCivIntervention: (id: string, intervention: CivIntervention) => typedError<string, string>(__TAURI_INVOKE("apply_civ_intervention", { id, intervention })),
	advanceCivTurn: (id: string) => typedError<string, string>(__TAURI_INVOKE("advance_civ_turn", { id })),
};

/* Types */
/**
 *  Events emitted by a supervised agent.
 * 
 *  This enum is the single event schema for both in-process channels (D-01)
 *  and NDJSON stdout serialization from child-process workers (D-04).
 *  All variants must remain serde-compatible — do NOT add non-serializable fields.
 */
export type AgentEvent = ({ StateChanged: AgentState }) & { Error?: never; ReasoningDelta?: never; TextDelta?: never; ToolCallCompleted?: never; ToolCallStarted?: never; TurnCompleted?: never } | ({ ToolCallStarted: {
	tool: string,
	input: string,
} }) & { Error?: never; ReasoningDelta?: never; StateChanged?: never; TextDelta?: never; ToolCallCompleted?: never; TurnCompleted?: never } | ({ ToolCallCompleted: {
	tool: string,
	output: string,
} }) & { Error?: never; ReasoningDelta?: never; StateChanged?: never; TextDelta?: never; ToolCallStarted?: never; TurnCompleted?: never } | ({ TurnCompleted: {
	usage: TokenUsage,
} }) & { Error?: never; ReasoningDelta?: never; StateChanged?: never; TextDelta?: never; ToolCallCompleted?: never; ToolCallStarted?: never } | ({ Error: {
	message: string,
} }) & { ReasoningDelta?: never; StateChanged?: never; TextDelta?: never; ToolCallCompleted?: never; ToolCallStarted?: never; TurnCompleted?: never } | ({ TextDelta: string }) & { Error?: never; ReasoningDelta?: never; StateChanged?: never; ToolCallCompleted?: never; ToolCallStarted?: never; TurnCompleted?: never } | 
/**
 *  Chain-of-thought delta from reasoning models (Kimi For Coding,
 *  DeepSeek-R1, …). Kept on a separate event so the UI can present it
 *  as a collapsible/muted block beside the main reply.
 */
({ ReasoningDelta: string }) & { Error?: never; StateChanged?: never; TextDelta?: never; ToolCallCompleted?: never; ToolCallStarted?: never; TurnCompleted?: never };

/**
 *  Stable identifier for a supervised agent.
 *  Newtype over String — use `AgentId::new()` to generate a unique id.
 */
export type AgentId = string;

/**
 *  Typed state machine for a supervised agent.
 * 
 *  Valid transitions (`can_transition_to` returns true):
 *  - Idle → Planning, Executing
 *  - Planning → Executing, Failed
 *  - Executing → Waiting, Done, Failed
 *  - Waiting → Executing, Failed
 *  - Done → (terminal — no transitions)
 *  - Failed → (terminal — no transitions)
 */
export type AgentState = "Idle" | "Planning" | "Executing" | 
/**  Blocked on a permission prompt or context pull. */
"Waiting" | "Done" | "Failed";

export type ApiKeyProviderStatus = {
	configured: boolean,
	source: string,
	error: string | null,
};

/**  Mechanical scores derived from response text (no LLM involved). */
export type AutoScores = {
	/**  1–10. Lower = more slop. Computed from regex phrase hits + em-dash density. */
	ai_slop_score: number | null,
	/**  1–10. Lower = too short or wall-of-text; higher = appropriate length. */
	brevity_score: number | null,
	/**  None = grader N/A. Some(true)/Some(false) = JSON parse outcome on full body. */
	json_valid: boolean | null,
	code_block_count: number,
	em_dash_count: number,
	word_count: number,
	char_count: number,
	/**  Phrases hit, e.g. "Certainly!", "I'd be happy to", "delve". */
	slop_hits: string[],
};

export type ChatMessage = {
	role: string,
	content: string,
};

export type CivCivilization = {
	/**  Stable civ id ("civ-1"…). Empty in legacy saves; backfilled on load. */
	id?: string,
	/**
	 *  Display name for this civ (defaults to the session/colony name for the
	 *  founding civ; the participant name for civs added later).
	 */
	name?: string,
	/**  The model governing this civ. */
	model?: string,
	/**  Hex colour for renderer tinting; assigned from `CIV_COLORS`. */
	color?: string,
	/**  Home column (spawn point) for camera focus and colony fallback centring. */
	spawn_x?: number,
	/**  Home region id (claimed at spawn). */
	home_region?: string,
	/**  `false` once the colony collapses (population hits 0). */
	alive?: boolean,
	/**  Diplomacy stance toward other civs: civ_id -> "ally|trade|neutral|hostile". */
	diplomacy?: { [key in string]: string },
	era: string,
	population: number,
	health: number | null,
	morale: number | null,
	resources: { [key in string]: number },
	techs: string[],
	policies: string[],
	score: CivScore,
};

export type CivDecisionAction = {
	type: string,
	resource?: string | null,
	workers?: number | null,
	building?: string | null,
	x?: number | null,
	y?: number | null,
	tech_id?: string | null,
	direction?: string | null,
	policy?: string | null,
	event_id?: string | null,
};

export type CivDisaster = {
	id: string,
	kind: string,
	epicenter_x: number,
	radius: number,
	intensity: number | null,
	remaining_turns: number,
};

export type CivEntity = {
	id: string,
	kind: string,
	name: string,
	x: number,
	y: number,
	health: number | null,
	mood: number | null,
	role: string,
	/**
	 *  Owning civ id. `None` = wild fauna / neutral (predators, prey, resource
	 *  flora). Every founder, building, and egg is tagged with its owning civ.
	 */
	civ_id?: string | null,
	/**  Expressed colour morph (e.g. "leucistic"). Empty for non-axolotls. */
	morph?: string,
	/**  Life stage: "egg" | "hatchling" | "juvenile" | "adult" | "elder". */
	stage?: string,
	/**  "f" | "m" | "" (eggs/buildings). */
	sex?: string,
	/**  Turns alive since hatching. */
	age?: number,
	/**  Display scale multiplier derived from stage + genetics. */
	size?: number | null,
	/**  Equipped accessory ids. */
	accessories?: string[],
	/**  Heritable traits (axolotls + eggs). */
	genes?: CivGenes | null,
	/**  Remaining turns until an egg hatches. */
	hatches_in?: number | null,
	/**  Parent ids (eggs + offspring). */
	parents?: string[],
	/**
	 *  What this entity is doing this turn — drives the renderer's action
	 *  animation. Emitted values: "" (ambient swim) | "gather" | "build" |
	 *  "explore" | "play" | "rest" | "egg". The renderer also handles "eat" if a
	 *  future turn emits it.
	 */
	activity?: string,
	/**  Optional tile the entity swims toward while performing its activity. */
	target_x?: number | null,
	target_y?: number | null,
};

/**
 *  World-wide environment state. Seasons drift and disasters that physically
 *  reshape the world land in W4; W1 only carries the state (a calm default) so
 *  the rest of the system can read it.
 */
export type CivEnvironment = {
	season: string,
	turn_of_season: number,
	temperature: number | null,
	water_level: number,
	disasters: CivDisaster[],
	forecast?: CivDisaster | null,
};

/**
 *  Heritable traits. `allele_a`/`allele_b` are the two carried colour alleles;
 *  the expressed morph is the dominant of the two.
 */
export type CivGenes = {
	allele_a: string,
	allele_b: string,
	size_gene: number | null,
	fertility: number | null,
	longevity: number | null,
	vigor: number | null,
};

export type CivIntervention = {
	kind: string,
	target: string,
	amount?: number | null,
	x?: number | null,
	y?: number | null,
	duration?: number | null,
	intensity?: number | null,
	entity_id?: string | null,
	accessory?: string | null,
	/**
	 *  Civ a resource grant/removal targets. `None` = the first living civ
	 *  (back-compat). Modifier interventions stay world-global regardless.
	 */
	civ_id?: string | null,
};

export type CivLogEntry = {
	turn: number,
	kind: string,
	title: string,
	body: string,
	created_at: number,
};

export type CivModelDecision = {
	intent: string,
	public_rationale: string,
	actions: CivDecisionAction[],
	ethics_note: string,
	expected_risks: string[],
};

export type CivModifier = {
	id: string,
	kind: string,
	label: string,
	polarity: string,
	remaining_turns: number,
	intensity: number | null,
};

export type CivRegion = {
	id: string,
	name: string,
	biome: string,
	x: number,
	y: number,
	width: number,
	height: number,
	/**
	 *  Owning civ id. None = unclaimed. Set at spawn for home regions; mutated by
	 *  claim/raid once combat lands (W6).
	 */
	owner?: string | null,
};

export type CivScore = {
	survival: number | null,
	ethics: number | null,
	intelligence: number | null,
	total: number | null,
};

export type CivSessionConfig = {
	name: string,
	model: string,
	seed?: number | null,
};

export type CivSessionMeta = {
	id: string,
	name: string,
	model: string,
	created_at: number,
	updated_at: number,
	turn: number,
	score: number | null,
};

export type CivSessionSnapshot = {
	id: string,
	name: string,
	seed: number,
	/**
	 *  Snapshot schema version. Legacy v1 saves are migrated on load (see
	 *  `parse_snapshot`); always `SCHEMA_VERSION` after a successful load.
	 */
	version?: number,
	created_at: number,
	updated_at: number,
	turn: number,
	world: CivWorld,
	/**
	 *  The competing civilizations sharing this world. v1 saves carried a single
	 *  `civilization`; migration wraps it as the one element here.
	 */
	civs?: CivCivilization[],
	/**
	 *  World-wide environment state (seasons, disasters). Populated lazily — old
	 *  saves default to a calm spring.
	 */
	environment?: CivEnvironment,
	/**  Global/world modifiers (observer buffs/debuffs and disaster after-effects). */
	modifiers: CivModifier[],
	log: CivLogEntry[],
};

export type CivTile = {
	x: number,
	y: number,
	terrain: string,
	resource?: string | null,
	amount: number,
	/**
	 *  Biome region this tile belongs to (empty for air/surface). Lets the
	 *  renderer colour-grade water and substrate per region.
	 */
	biome?: string,
};

export type CivWorld = {
	width: number,
	height: number,
	tiles: CivTile[],
	entities: CivEntity[],
	/**
	 *  Named biome regions painted across the seabed. `owner` is the civ id that
	 *  holds the region (None = unclaimed).
	 */
	regions?: CivRegion[],
};

/**  A child entry inside a browsed directory. */
export type DirChild = {
	name: string,
	path: string,
	is_dir: boolean,
	is_hidden: boolean,
	is_symlink: boolean,
	is_package: boolean,
	/**  `true` for `.pdf` files — the UI offers one-click conversion. */
	is_pdf: boolean,
};

/**  A single level of a directory, for the in-app file browser. */
export type DirListing = {
	path: string,
	parent: string | null,
	children: DirChild[],
};

export type EvalArtifactFileInput = {
	relative_path: string,
	content: string,
};

export type EvalArtifactLaunchResult = {
	artifact_dir: string,
	entry_path: string,
	message: string,
};

export type EvalArtifactRequest = {
	label: string,
	kind: string,
	entry_path: string,
	files: EvalArtifactFileInput[],
};

export type EvalMeta = {
	id: string,
	prompt: string,
	models: string[],
	created_at: number,
	manual_review_count?: number,
	suite_id?: string | null,
	suite_run_id?: string | null,
};

export type EvalResult = EvalResult_Serialize | EvalResult_Deserialize;

export type EvalResult_Deserialize = {
	id: string,
	prompt: string,
	models: string[],
	results: ModelEvalResult[],
	human_scores: { [key in string]: HumanScores },
	/**  Personal review notes and manual score. Separate from blind eval scoring. */
	manual_reviews?: { [key in string]: ManualReview },
	auto_scores?: { [key in string]: AutoScores },
	judge?: JudgeScores | null,
	/**
	 *  Per-model captured reasoning_content stream (chain-of-thought). Empty
	 *  string for models that don't expose reasoning.
	 */
	reasoning_traces?: { [key in string]: string },
	/**  Per-model goal grade (5 axes + flags). Populated by run_goal_grade. */
	goal_grades?: { [key in string]: GoalGrade },
	/**
	 *  True if this eval was started via start_goal_eval (so the UI/grader
	 *  knows to apply the goal rubric).
	 */
	is_goal_eval?: boolean,
	/**
	 *  The original goal text (== prompt when is_goal_eval). Kept distinct for
	 *  future variants that wrap the goal in extra framing.
	 */
	goal?: string | null,
	/**  If part of a suite run, the suite id (e.g. "reasoning"). None for ad-hoc evals. */
	suite_id?: string | null,
	/**  If part of a suite run, groups prompts together by the same run id. */
	suite_run_id?: string | null,
	/**  If part of a suite run, the SuitePrompt.id for this row. */
	suite_prompt_id?: string | null,
	/**
	 *  Per-model reliability/calibration signals (tokens, cost, tok/s,
	 *  token-count error). Captured at run time and persisted so the P6
	 *  profile aggregator can read past runs. `None` (absent) for eval files
	 *  that predate metric capture or runs that produced no model results —
	 *  kept distinct from `Some({})` so a read-mutate-write of an old eval
	 *  (judge / goal-grade) never fabricates an empty-but-present block.
	 */
	reliability_metrics?: { [key in string]: ReliabilityMetrics } | null,
	created_at: number,
};

export type EvalResult_Serialize = {
	id: string,
	prompt: string,
	models: string[],
	results: ModelEvalResult[],
	human_scores: { [key in string]: HumanScores },
	/**  Personal review notes and manual score. Separate from blind eval scoring. */
	manual_reviews: { [key in string]: ManualReview },
	auto_scores: { [key in string]: AutoScores },
	judge: JudgeScores | null,
	/**
	 *  Per-model captured reasoning_content stream (chain-of-thought). Empty
	 *  string for models that don't expose reasoning.
	 */
	reasoning_traces: { [key in string]: string },
	/**  Per-model goal grade (5 axes + flags). Populated by run_goal_grade. */
	goal_grades: { [key in string]: GoalGrade },
	/**
	 *  True if this eval was started via start_goal_eval (so the UI/grader
	 *  knows to apply the goal rubric).
	 */
	is_goal_eval: boolean,
	/**
	 *  The original goal text (== prompt when is_goal_eval). Kept distinct for
	 *  future variants that wrap the goal in extra framing.
	 */
	goal: string | null,
	/**  If part of a suite run, the suite id (e.g. "reasoning"). None for ad-hoc evals. */
	suite_id: string | null,
	/**  If part of a suite run, groups prompts together by the same run id. */
	suite_run_id: string | null,
	/**  If part of a suite run, the SuitePrompt.id for this row. */
	suite_prompt_id: string | null,
	/**
	 *  Per-model reliability/calibration signals (tokens, cost, tok/s,
	 *  token-count error). Captured at run time and persisted so the P6
	 *  profile aggregator can read past runs. `None` (absent) for eval files
	 *  that predate metric capture or runs that produced no model results —
	 *  kept distinct from `Some({})` so a read-mutate-write of an old eval
	 *  (judge / goal-grade) never fabricates an empty-but-present block.
	 */
	reliability_metrics?: { [key in string]: ReliabilityMetrics } | null,
	created_at: number,
};

export type EvalSuite = {
	id: string,
	name: string,
	description: string,
	prompts: SuitePrompt[],
};

export type FileDiff = {
	path: string,
	old_content: string,
	new_content: string,
};

/**  One axis of the goal rubric (1–5 with an evidence quote from the reasoning). */
export type GoalAxisScore = {
	score: number | null,
	evidence: string,
};

/**  Per-model goal grade with the 5 reasoning axes, flags and a one-line summary. */
export type GoalGrade = {
	judge_model: string,
	/**
	 *  Keyed by axis: "goal_decomposition", "assumption_quality",
	 *  "self_correction", "plan_action_coherence", "goal_achievement".
	 */
	axes: { [key in string]: GoalAxisScore },
	flags: ReasoningFlag[],
	summary: string,
};

export type GroupLaunchResult = {
	group_id: string,
	agent_ids: string[],
	branches: string[],
};

/**  Proposed hint overrides for one model. Empty `proposals` = no change advised. */
export type HintProposal = {
	model: string,
	/**  Total runs the profile aggregated. */
	runs: number,
	/**  0.0–1.0 confidence from the sample size (saturates at 20 runs). */
	confidence: number | null,
	proposals: ProposedOverride[],
	/**  Human-facing summary (stability warnings, "no changes", etc.). */
	note: string,
};

export type HumanScores = {
	accuracy: number | null,
	helpfulness: number | null,
	quality: number | null,
	creativity: number | null,
	design: number | null,
	/**  1–10. Visual/structural beauty: hierarchy, code-block formatting, whitespace. */
	aesthetics: number | null,
	/**  1–10. 1 = full of clichés ("certainly!", em-dash spam, "delve"); 10 = clean prose. */
	ai_slop: number | null,
	/**  1–10. Appropriate concision (penalize wall-of-text and excessive hedging). */
	brevity: number | null,
};

/**  LLM-judge output for a single eval. */
export type JudgeScores = {
	judge_model: string,
	/**  Per-model rubric scores assigned by the judge. */
	scores: { [key in string]: HumanScores },
	/**  Per-model one-line rationale from the judge. */
	rationale: { [key in string]: string },
};

export type MacGlobalHotkeySettings = {
	enabled: boolean,
	shortcut: string,
};

export type MacNotificationSettings = {
	agent_finished: boolean,
	eval_finished: boolean,
	permission_required: boolean,
};

export type MacProductivitySettings = {
	external_editor: string | null,
	global_hotkey: MacGlobalHotkeySettings,
	notifications: MacNotificationSettings,
};

/**  User-authored post-eval review, intentionally separate from blind rubric scores. */
export type ManualReview = {
	score?: number | null,
	notes?: string,
	updated_at?: number,
};

/**
 *  Single MCP server entry as stored in `mcp.json`.
 *  Two transports: `stdio` (default — spawn a process) or `http` (remote SSE/HTTP).
 */
export type McpServerConfig = {
	name: string,
	/**  "stdio" | "http"  (defaults to stdio if absent in raw json). */
	transport: string,
	/**  For stdio: the executable. For http: ignored. */
	command?: string | null,
	args?: string[],
	env?: { [key in string]: string },
	/**  For http: the URL. */
	url?: string | null,
	headers?: { [key in string]: string },
	/**  "user" | "project" — which config file declared this server. */
	scope: string,
};

export type McpTestResult = {
	ok: boolean,
	message: string,
	/**  Round-trip latency in ms (None on failure). */
	latency_ms: number | null,
};

export type ModelEvalResult = {
	model: string,
	content: string,
	input_tokens: number,
	output_tokens: number,
	duration_ms: number,
	error: string | null,
};

/**
 *  Frontend-facing decision type with three options (D-12).
 *  Distinct from PermissionPromptDecision in runtime — that type drives the Rust outcome.
 */
export type PermissionDecision = "Allow" | "Deny" | "AlwaysAllow";

/**  Summary returned after (re)building the per-model reliability profiles. */
export type ProfileBuildResult = {
	/**  Distinct models that got a profile written. */
	models: number,
	/**  Total per-model records aggregated across all eval files. */
	records: number,
	/**  Eval files that contributed at least one reliability record. */
	evals_scanned: number,
	/**  Absolute path of the profiles directory written to. */
	profiles_dir: string,
};

/**  A quick-access working directory the user has opened in the app. */
export type Project = {
	/**  Absolute, canonicalized directory path. */
	path: string,
	/**  Display name (last path component). */
	name: string,
	added_at: number,
	last_opened_at: number,
};

export type PromptCommand = {
	command: string,
	description: string,
	scope: string,
	source_path: string,
	content: string,
};

/**  Summary returned after (re)building the propose-only hint overrides. */
export type ProposalBuildResult = {
	/**  Models a proposal file was written for. */
	models: number,
	/**  Total field overrides proposed across all models. */
	overrides: number,
	/**  Absolute path of the proposals directory written to. */
	proposals_dir: string,
};

/**  A single proposed override of one `ModelHints` field. */
export type ProposedOverride = {
	/**  `ModelHints` field name, e.g. `"max_completion_tokens"`. */
	field: string,
	/**  Current shipped value, rendered as a string. */
	current: string,
	/**  Proposed value, rendered as a string. */
	proposed: string,
	/**  Why the change is proposed, citing the observed signal. */
	rationale: string,
};

/**
 *  A flag raised against a chunk of reasoning. Emitted live by the supervisor
 *  during streaming, and/or in batch by the post-hoc grader.
 */
export type ReasoningFlag = {
	/**  e.g. "bad_assumption" | "goal_drift" | "premature_commit" | "no_verification" | "good_decomposition" */
	kind: string,
	/**  "info" | "warn" | "error" */
	severity: string,
	/**  A short quote from the reasoning that triggered the flag. */
	quote: string,
	/**  Why the flag was raised. */
	comment: string,
	/**  Char offset into the reasoning trace where `quote` begins (best-effort). */
	offset_chars: number,
};

/**
 *  Per-model reliability and calibration signals produced by a single eval run.
 * 
 *  These are the §5 metrics the single-turn eval-lab can actually produce
 *  (tokens/cost/token-count-error/duration/throughput) — the agentic
 *  edit-apply / tool-call metrics come from the separate bench harness. Cost
 *  and the token estimate are computed with the authoritative `runtime`
 *  pricing + tokenizer so they match the CLI engine, not a UI approximation.
 */
export type ReliabilityMetrics = {
	model: string,
	/**  Provider-reported input/output tokens for the turn (authoritative for cost). */
	input_tokens: number,
	output_tokens: number,
	duration_ms: number,
	/**  Output tokens per wall-clock second; 0 when duration or output is 0. */
	tokens_per_sec: number | null,
	/**
	 *  Dollar cost from the `runtime` pricing table. 0 when the model has no
	 *  verified pricing (see `cost_known`) — never an Opus-rate guess.
	 */
	cost_usd: number | null,
	/**
	 *  False when the model has no verified pricing entry, so `cost_usd` is a
	 *  genuine "unknown" rather than a real $0.
	 */
	cost_known: boolean,
	/**  `runtime` tokenizer estimate of the response, for the model's family. */
	estimated_output_tokens: number,
	/**
	 *  |estimate − reported| / reported. 0 when reported output is 0. The §5
	 *  "token-count error" signal (target ≤ 5%).
	 */
	token_count_error: number | null,
	/**  Characters of streamed chain-of-thought (0 for non-reasoning models). */
	reasoning_chars: number,
	/**  True when the provider returned an error for this model. */
	had_error: boolean,
};

/**
 *  Aggregate reliability profile for one model, computed from many runs.
 * 
 *  Means are taken over *successful* runs only (a provider error yields zero
 *  tokens/duration and would otherwise skew throughput and calibration). Cost
 *  is summed across all runs.
 */
export type ReliabilityProfile = {
	model: string,
	/**  Total runs aggregated (successful + errored). */
	runs: number,
	/**  Runs that did not return a provider error. */
	successful_runs: number,
	/**  Fraction of runs that returned a provider error (0.0–1.0). */
	error_rate: number | null,
	/**  Mean output throughput over successful runs (tok/s). */
	mean_tokens_per_sec: number | null,
	/**  Mean relative token-count error over successful runs (0.0+). */
	mean_token_count_error: number | null,
	/**  Fraction of successful runs whose token-count error ≤ 5% (the §5 target). */
	token_calibration_rate: number | null,
	/**  True only if every aggregated run had verified pricing. */
	cost_known: boolean,
	/**  Total computed dollar cost across all aggregated runs. */
	total_cost_usd: number | null,
	/**  Mean reported output tokens over successful runs. */
	mean_output_tokens: number | null,
	/**  Mean reasoning-trace length (chars) over successful runs. */
	mean_reasoning_chars: number | null,
};

export type RoleConfig = {
	role: string,
	task: string,
	model: string,
};

export type SessionMeta = {
	id: string,
	title: string,
	created_at: number,
};

export type SkillManifest = {
	/**  Short kebab-case slug (also the directory name). */
	name: string,
	/**  One-line summary shown in the UI and prepended to the chat system prompt. */
	description: string,
	/**  Path to the SKILL.md on disk (for "open in editor" actions later). */
	path: string,
	/**  Body length in bytes (so the UI can warn about large skills). */
	body_bytes: number,
	/**  Optional list of tools the skill says it needs — informational only for now. */
	allowed_tools?: string[],
	/**  Optional invocation triggers — informational hints to the model. */
	triggers?: string[],
};

export type SuitePrompt = {
	id: string,
	prompt: string,
	/**  "ai_slop" | "brevity" | "json_mode" | "code" | "refusal" | "visual" | "free" */
	grader: string,
};

/**  Metadata for one terminal, returned to the frontend. */
export type TerminalInfo = {
	id: string,
	shell: string,
	shell_name: string,
	cwd: string,
	env_source: string,
};

export type TokenUsage = {
	input_tokens: number,
	output_tokens: number,
	cache_creation_input_tokens: number,
	cache_read_input_tokens: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

