use std::fs;
use std::path::{Path, PathBuf};
use std::sync::RwLock;

pub mod vault;

pub use vault::ObsidianVault;

#[derive(Debug, Clone)]
pub struct MemoryConfig {
    pub enabled: bool,
    pub vault_path: Option<PathBuf>,
    pub auto_write_session_summaries: bool,
    pub auto_write_learnings: bool,
    pub max_retrieval_results: usize,
    pub max_context_tokens: usize,
}

impl Default for MemoryConfig {
    fn default() -> Self {
        Self {
            enabled: true,
            vault_path: None,
            auto_write_session_summaries: true,
            auto_write_learnings: true,
            max_retrieval_results: 5,
            max_context_tokens: 2000,
        }
    }
}

#[derive(Debug, Clone)]
pub struct SessionNote {
    pub title: String,
    pub date: String,
    pub task: String,
    pub phase: Option<String>,
    pub complexity: Option<String>,
    pub models: Vec<String>,
    pub files_changed: Vec<String>,
    pub duration_seconds: Option<u64>,
    pub content: String,
    pub tags: Vec<String>,
}

impl SessionNote {
    pub fn to_markdown(&self) -> String {
        let mut md = String::new();
        md.push_str("---\n");
        md.push_str(&format!("date: {}\n", self.date));
        md.push_str(&format!("task: \"{}\"\n", self.task));
        if let Some(ref phase) = self.phase {
            md.push_str(&format!("phase: {}\n", phase));
        }
        if let Some(ref complexity) = self.complexity {
            md.push_str(&format!("complexity: {}\n", complexity));
        }
        if !self.models.is_empty() {
            md.push_str(&format!("models: [{}]\n", self.models.join(", ")));
        }
        if !self.files_changed.is_empty() {
            md.push_str(&format!("files: [{}]\n", self.files_changed.join(", ")));
        }
        if let Some(dur) = self.duration_seconds {
            md.push_str(&format!("duration_seconds: {}\n", dur));
        }
        md.push_str("---\n\n");
        md.push_str(&format!("# Session: {}\n\n", self.title));
        md.push_str(&self.content);
        md.push_str("\n\n---\n");
        md.push_str("*Generated by claw-code v");
        md.push_str(env!("CARGO_PKG_VERSION"));
        md.push_str("*\n");
        md
    }
}

#[derive(Debug, Clone)]
pub struct MemorySystem {
    vault: Option<ObsidianVault>,
    config: MemoryConfig,
}

impl MemorySystem {
    pub fn new(config: MemoryConfig) -> Self {
        let vault = config.vault_path.as_ref().map(|p| ObsidianVault::new(p.clone()));
        Self { vault, config }
    }

    pub fn discover_vault() -> Option<PathBuf> {
        vault::discover_vault()
    }

    pub fn is_enabled(&self) -> bool {
        self.config.enabled && self.vault.is_some()
    }

    pub fn write_session_note(&self, note: &SessionNote) -> Result<PathBuf, std::io::Error> {
        match &self.vault {
            Some(vault) => vault.write_session_note(note),
            None => Err(std::io::Error::new(
                std::io::ErrorKind::NotFound,
                "Obsidian vault not configured",
            )),
        }
    }

    pub fn search_notes(&self, query: &str) -> Result<Vec<PathBuf>, std::io::Error> {
        match &self.vault {
            Some(vault) => vault.search_notes(query),
            None => Ok(Vec::new()),
        }
    }

    pub fn get_recent_sessions(&self, limit: usize) -> Result<Vec<PathBuf>, std::io::Error> {
        match &self.vault {
            Some(vault) => vault.get_recent_sessions(limit),
            None => Ok(Vec::new()),
        }
    }

    pub fn read_note(&self, path: &Path) -> Result<String, std::io::Error> {
        match &self.vault {
            Some(vault) => vault.read_note(path),
            None => Err(std::io::Error::new(
                std::io::ErrorKind::NotFound,
                "Obsidian vault not configured",
            )),
        }
    }

    pub fn vault_status(&self) -> Option<(PathBuf, usize)> {
        self.vault.as_ref().map(|v| v.status())
    }
}

impl Default for MemorySystem {
    fn default() -> Self {
        Self::new(MemoryConfig::default())
    }
}
